### ISSUE TITLE
Detecting aborted transaction

### ISSUE THREAD

**Issue by DomHoney** [eugene-eeo/tinyrecord#8]
Hi, thanks for this useful library, it solves a lot of problems for me.

I'm not well versed with Python, but from what I can understand the `tinyrecord.transaction` class suppresses the `AbortSignal` in the event a transaction fails (`tinyrecord.transaction.__exit__`).

I can see the docstring in the `AbortSignal`class states "It is ignored when raised within the body of a transaction.", so I can tell this behaviour is by design.

Given this behaviour, I think I'm missing something obvious but I'm not sure how to check whether a transaction failed without querying the table I was attempting to update.

Regards

**Comment by eugene-eeo** [comment]
Hi, yes, aborting transactions manually using the `abort()` function does not raise an exception by design. The reason being, if a transaction fails in some other way, the exception raised will most certainly _not_ be `AbortSignal`, so `abort()` is useful for situations where you want to explicitly abandon a transaction midway, _but raise no errors_.

If you want to detect when custom errors occur you can always raise your own exception:

```python
class MyException(Exception):
    pass

with transaction(...) as txn:
    # ...
    if error_condition:
        raise MyException()
```

**Comment by DomHoney** [comment]
Thank you, I now see where I went wrong - I thought that `AbortSignal` could be raised from within `Changeset.execute()` and with that assumption you could see why I was confused!

Thank you for your quick response.
